---
title: "MA 331 Final Project"
author: "Josh Gribbon"
date: "December 11, 2017"
output:
  html_document: default
  html_notebook: default
geometry: margin=2cm
fig_width: 4
fig_height: 3
---

```{r}
#load in data from csv
ds = read.csv("~/Downloads/pcb.csv")
pcb138 = ds[[2]]
pcb153 = ds[[3]]
pcb180 = ds[[4]]
pcb28 = ds[[5]]
pcb52 = ds[[6]]
pcb126 = ds[[7]]
pcb118 = ds[[8]]
pcb = ds[[9]]
teq = ds[[10]]
teqpcb = ds[[11]]
teqdioxin = ds[[12]]
teqfuran = ds[[13]]
df = data.frame(pcb138,pcb153,pcb180,pcb28,pcb52,pcb126,pcb118,pcb,teq,teqpcb,teqdioxin,teqfuran)

repl_zs <- function(col){
  #replaces zeros in a column with half of the minimum positive value
  min_val=min(col[col>0])
  col[col==0] <- (min_val/2)
  col
}

df2 = data.frame(pcb)

for(i in names(df)){
  col_name=paste("log-replaced", i)
  col=log(repl_zs(df[[i]]))
  df2[[i]] <- col
  print(paste("Summary of", col_name))
  print(summary(col))
  boxplot(col, main=paste("Boxplot of", col_name))
}
```

```{r}
plot(df2[,c(1,2)])
plot(df2[,c(1,3)])
plot(df2[,c(1,4)])
plot(df2[,c(1,5)])
plot(df2[,c(1,6)])
plot(df2[,c(1,7)])
plot(df2[,c(1,8)])
plot(df2[,c(2,3)])
plot(df2[,c(2,4)])
plot(df2[,c(2,5)])
plot(df2[,c(2,6)])
plot(df2[,c(2,7)])
plot(df2[,c(2,8)])
plot(df2[,c(3,4)])
plot(df2[,c(3,5)])
plot(df2[,c(3,6)])
plot(df2[,c(3,7)])
plot(df2[,c(3,8)])
plot(df2[,c(4,5)])
plot(df2[,c(4,6)])
plot(df2[,c(4,7)])
plot(df2[,c(4,8)])
plot(df2[,c(5,6)])
plot(df2[,c(5,7)])
plot(df2[,c(5,8)])
plot(df2[,c(6,7)])
plot(df2[,c(6,8)])
plot(df2[,c(7,8)])
```

```{r}
lm1=lm(pcb~pcb52+pcb118+pcb138+pcb180, data=ds)
coef(lm1)
summary(lm1)
residuals(lm1)
plot(pcb52, residuals(lm1))
plot(pcb118, residuals(lm1))
plot(pcb138, residuals(lm1))
plot(pcb180, residuals(lm1))
```





















